name: route_task
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.2.3
# Responsive UI
  flutter_screenutil: ^5.9.3 
# Networking
  http: ^1.2.1
  dartz: ^0.10.1
  connectivity_plus: ^6.0.1
# State Management  
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
# Dependecy Injection 
  get_it: ^7.7.0
  injectable: ^2.4.2


  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
